### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SubfieldBase'

### ISSUE THREAD

**Issue by hyusetiawan** [silverapp/silver#396]
I am getting the error above on a clean install after running migrate. I am using Django==1.10.4 and
Please advise.

**Comment by bogdanpetrea** [comment]
Hi @hyusetiawan, Silver has not been tested to work with Django 1.10.

This might be because of the JSONField implementation we are using, which is based on models.SubFieldBase, which has been deprecated in Django 1.9 and removed in Django 1.10.

Try using django-jsonfield==1.0.0 or newer and see if it works.

**Comment by loxllxol** [comment]
Any chance this issue has been resolved?
